Exporting a PooledConnection type for mobc
weiznich/diesel_async pull request #123
Opened 2023-10-26 10:24 UTC by bausano

Some projects can avoid specifying `mobc` dependency by reusing this exported type. Also aligns `mobc` module more with its alternatives `deadpool` and `bb8`.

2023-10-26 11:00 UTC, weiznich requested changes
Thanks for opening this PR:+1:

I would like to exclude any version related change from this PR there will likely not be a release today.

2023-10-26 11:00 UTC, weiznich commented on CHANGELOG.md
> +## [0.4.2] - 2023-10-26
```suggestion
## Unreleased
```

2023-10-26 11:00 UTC, weiznich commented on Cargo.toml
> -version = "0.4.1"
That shouldn't be changed yet.

2023-10-26 13:31 UTC, bausano commented on CHANGELOG.md
> +## [0.4.2] - 2023-10-26
Done

2023-10-26 13:32 UTC, bausano commented on Cargo.toml
> -version = "0.4.1"
Done

2023-10-27 05:09 UTC, weiznich approved these changes

2023-10-27 05:09 UTC, merged